13th increment
UndeadDemidov/yandex-praktikum pull request #13
Opened 2022-05-29 06:11 UTC by UndeadDemidov

13th increment is done

2022-05-29 07:15 UTC, UndeadDemidov commented
Честно говоря не хватило времени (а я потратил сильно больше заявленных 17 часов) для
1. Написания тестов, хотя очень хотелось. Хорошо, что у меня есть опыт написания тестов для go даже для базы данных с моками БД.
2. Не успел сделать обработку пакета ссылок для сокращения stream style, потому что залип на том, чтобы сделать обработку конфликта для пакетной же обработки

формально спринт выполнен, но технический долг остался - будем считать, что это демонстрация того, как бывает в реальных проектах :)

2022-05-31 11:32 UTC, blattaria7 commented on internal/app/storages/database.go
> +	defer tx.Rollback()
метод `Rollback()` возвращает ошибку, ее необходимо обработать)

2022-05-31 12:09 UTC, blattaria7 requested changes
Привет) Как всегда - отличная работа)) Мне нравится как реализованы новые инкременты, а еще я очень рада видеть в коде логи)
И отдельное спасибо за комментарии =)

Я оставила несколько замечаний, большинство из них косметика. Но есть момент связанный с реализацией утиной типизации, надо его поправить, чтобы все было максимально по-гошному) 
Насчет техдолга - у нас тут такая позиция у курса моделировать "боевые" условия, получается все реалистично :D 
Буду ждать работу =)

2022-05-31 12:09 UTC, blattaria7 commented on internal/app/storages/database.go
> +// Или я не прав - и для Go так нормально???
да, можно оставлять так)

2022-05-31 12:09 UTC, blattaria7 commented on internal/app/storages/file.go
> +			// Либо опять по всему файлу бежать с unmarshal
обычно юзают его)

2022-05-31 19:49 UTC, UndeadDemidov commented
Посмотрел пример проекта. Положил себе в закладки, много полезного для себя нашел.
По поводу выделения слоя сервиса, как бизнес логики и слоя http, как представления ее уже неделю думаю. Но побоялся залипнуть там надолго. Надо наверно сделать.

Итого мой ToDo в поисках Дзен
1. выделение слоя сервиса с бизнес логикой
2. stream style для batch: read-buffer-write
3. дописать юнит тесты - не лишняя практика

2022-06-02 08:57 UTC, blattaria7 approved these changes

2022-06-05 15:09 UTC, merged